# Generated by Django 3.2.5 on 2022-01-27 02:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PostTable',
        ),
    ]
