# Generated by Django 3.2.5 on 2022-01-22 14:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registration', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MovieTable',
            fields=[
                ('movie_id', models.IntegerField(primary_key=True, serialize=False)),
                ('movie_title', models.CharField(max_length=100)),
                ('movie_image_info', models.ImageField(blank=True, upload_to='images/')),
                ('genre_tag', models.CharField(choices=[('AO', 'Action'), ('RE', 'Romance'), ('HR', 'Horror'), ('CY', 'Comedy'), ('DA', 'Drama')], max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('post_image', models.ImageField(blank=True, upload_to='images/')),
                ('post_contents', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post_detail.movietable')),
                ('recommender', models.ManyToManyField(related_name='recommend_user', to='registration.User')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='registration.user')),
            ],
        ),
    ]
