# Generated by Django 3.2.5 on 2022-01-22 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('post_detail', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posttable',
            name='recommender',
            field=models.ManyToManyField(null=True, related_name='recommend_user', to='registration.User'),
        ),
    ]
