# Generated by Django 3.2.5 on 2022-01-22 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registration', '0001_initial'),
        ('post_detail', '0002_alter_posttable_recommender'),
    ]

    operations = [
        migrations.RenameField(
            model_name='posttable',
            old_name='movie_id',
            new_name='movie_genres',
        ),
        migrations.AddField(
            model_name='posttable',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='posttable',
            name='recommender',
            field=models.ManyToManyField(blank=True, related_name='recommend_user', to='registration.User'),
        ),
    ]
