# Generated by Django 4.0.1 on 2022-01-23 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_remove_movie_created'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre_tag',
            field=models.CharField(choices=[('action', 'Action'), ('romance', 'Romance'), ('horror', 'Horror'), ('comedy', 'Comedy'), ('drama', 'Drama')], max_length=10),
        ),
    ]
