# Generated by Django 4.0.1 on 2022-01-25 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_movie_movie_trailer'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_trailer',
            field=models.URLField(default=''),
        ),
    ]
