# Generated by Django 4.0.1 on 2022-01-25 08:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_movie_video'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='movie_trailer',
        ),
    ]
