# Generated by Django 4.0.1 on 2022-01-25 14:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myinfo', '0001_initial'),
        ('main', '0011_remove_movie_movie_trailer'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='movie',
            name='video',
        ),
        migrations.CreateModel(
            name='PostTable',
            fields=[
                ('post_id', models.AutoField(primary_key=True, serialize=False)),
                ('post_title', models.CharField(max_length=50)),
                ('post_image', models.ImageField(blank=True, upload_to='images/')),
                ('post_contents', models.TextField(max_length=1000)),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('modify_date', models.DateTimeField(blank=True, null=True)),
                ('movie_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.movie')),
                ('recommender', models.ManyToManyField(blank=True, related_name='recommend_user', to='myinfo.UserTable')),
                ('user_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_user', to='myinfo.usertable')),
            ],
        ),
        migrations.CreateModel(
            name='CommentTable',
            fields=[
                ('comment_id', models.AutoField(primary_key=True, serialize=False)),
                ('content', models.TextField(max_length=1000)),
                ('create_date', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='myinfo.usertable')),
                ('post_table', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.posttable')),
            ],
        ),
    ]
