# Generated by Django 4.0.1 on 2022-01-23 10:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_movie_created'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='created',
        ),
    ]
