# Generated by Django 4.0.1 on 2022-01-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_alter_movie_genre_tag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='status',
            field=models.CharField(choices=[('RA', 'RECENTLY ADDED'), ('MC', 'MOST COMMENTED'), ('TR', 'TOP RATED')], max_length=2),
        ),
    ]
