# Generated by Django 4.0.1 on 2022-01-25 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_remove_movie_slug_remove_movie_video_posttable_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posttable',
            name='movie_id',
        ),
        migrations.RemoveField(
            model_name='posttable',
            name='recommender',
        ),
        migrations.RemoveField(
            model_name='posttable',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='CommentTable',
        ),
        migrations.DeleteModel(
            name='PostTable',
        ),
    ]
