# Generated by Django 4.0.1 on 2022-01-26 06:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0014_movie_movie_image_bg'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='movie_image_bg',
            field=models.ImageField(null=True, upload_to='images'),
        ),
    ]
